// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using SuperCoolApp2.Models;
using System;

namespace SuperCoolApp2.Migrations
{
    [DbContext(typeof(SuperCoolApp2Context))]
    partial class SuperCoolApp2ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.1-rtm-125")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SuperCoolApp2.Models.Image", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Caption");

                    b.Property<byte[]>("ImageFileContent");

                    b.Property<int?>("ImageId1");

                    b.Property<string>("Title");

                    b.Property<string>("Url");

                    b.HasKey("ImageId");

                    b.HasIndex("ImageId1");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("SuperCoolApp2.Models.Image", b =>
                {
                    b.HasOne("SuperCoolApp2.Models.Image")
                        .WithMany("ImageList")
                        .HasForeignKey("ImageId1");
                });
#pragma warning restore 612, 618
        }
    }
}
